#
###################################
# Site wide configuration
####################################
#
title: Shayan Eskandari
email: me@shayan.es
description: Shayan Eskandari Website - CTFO / Head of Security.
url: https://shayan.es # the base hostname & protocol for your site
keywords: ["Shayan Eskandari","Shayan", "Eskandari" ,"Blockchain", "Security", "Bitcoin", "Ethereum", "Engineer", "Decentralization", "STS"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Shayan Eskandari
  avatar: shayan.jpeg
  job: "PhD / Head of Security"
  bio: "Based in Toronto ðŸ‡¨ðŸ‡¦"
  email: me@shayan.es
  #disqus-shortname: renyuanzblog
  twitter: sbetamc #username
  facebook: #username
  google:
    plus: #username
    analytics: G-PBFCXL9V1S
    verify:
    ad-client:
    ad-slot:
    site-verification: "eXNCznk_xXFAGUB-CyrLeDiuWaP8H5VUUdPTBvVAozg"
  bing-verify:
  github: shayanb #username
  stackoverflow: 1402429/shayan  # from a "http://stackoverflow.com/users/123456/username" link
  linkedin: shayane #username
  xing: #username
  medium: sbetamc
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: sbetamc
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  # blog: http://blog.theshayan.com/
  googlescholar: K9xYnSQAAAAJ
